name: Update HTB Card

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  update-card:
    permissions:
      contents: write

    uses: jjimenezgarcia/htb-readme-card/.github/workflows/htb-readme-card.yml@main

    with:
      profile_id: 019dcc3b-1360-710a-b951-137599456ed5
      output_file: assets/htb-card.svg